server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  variables:
    admin: "ROLE_ADMIN"
    owner: "ROLE_OWNER"
    employee: "ROLE_EMPLOYEE"
    client: "ROLE_CUSTOMER"





